# 服务端口号
server:
  port: 8080

spring:
  application:
    name: e2echo-server
  cloud:
    nacos:
      server-addr: localhost:8848
  jackson:
    time-zone: GMT+8
  datasource:
    # MySQL 相关配置
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/e2echo_server?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: root
    password: root
    hikari:
      # 自动检测连接
      connection-test-query: SELECT 1
      # 数据库连接超时时间,默认30秒
      connection-timeout: 60000
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 500000
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 540000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 12
      # 最小空闲连接数量
      minimum-idle: 10
      # 连接池名称
      pool-name: SPHHikariPool
  rabbitmq:
    # 主机名
    host: localhost
    # 端口
    port: 5672
    # 虚拟主机
    virtual-host: e2echo
    # 登入用户名
    username: guest
    # 登入密码
    password: guest
  redis:
    host: localhost # Redis 主机地址
    port: 6379 # Redis 端口
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

#用于打印框架生成的sql语句，便于调试
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  # 默认是false，需要设置为true
  default-flat-param-object: true

minio:
  endpoint: http://127.0.0.1:9000 # MinIO服务地址
  bucketName: e2echo # 存储桶名称
  accessKey: minioadmin # 访问密钥
  secretKey: minioadmin # 秘密密钥
